-- schema used in JUnit tests -> this script is executed at the beginning of JUnit suite
CREATE SEQUENCE public.users_pk_seq AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE TABLE public.users (
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE users_pk_seq PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50),
  birth_date DATE,
  time_of_death TIMESTAMP,
  column_with_default INTEGER DEFAULT 100
);